version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectdb
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/projectdb